config/routes.rb
Rails.application.routes.draw do
  root "home_pages#home"
  
  devise_for :users
  namespace :admin do
    resources :users, only: [:index, :destroy, :update]
    resources :categories
    resources :products, except: :show
    resources :suggestions, only: [:index, :update, :destroy]
  end
  resources :suggestions, except: [:edit, :update, :show]
  resources :products, only: [:index, :show]
  resources :carts, except: [:edit, :update, :show]
  resources :users, only: [:show]
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def index
    @cart = session[:cart] ? session[:cart] : Hash.new
    @products = @cart.map {|id, quantity| [Product.find_by(id: id), quantity]}
  end

  def new
    session[:cart] = nil
    redirect_to carts_path
  end
  
  def create
    id = params[:product_id]
    session[:cart] = session[:cart] ||= Hash.new
    quantity = params[:quantity]
    @cart = session[:cart]
    @cart[id] = @cart[id] ? (@cart[id].to_i + quantity.to_i) : quantity.to_i
    redirect_to carts_path
  end
 
  def destroy
    session[:cart].delete params[:id]
    flash[:success] = t ".delete_successful"
    redirect_to carts_path
  end
end

app/views/carts/_item.html.erb
<% @products.each do |product, quantity| %>
  <% if product %>
    <tr>
      <td class="center">
        <%= link_to product do %>
          <%= image_tag product.image, alt: product.name,
            class: "product-thumbnail", size: Settings.cart.size %>
          <%= product.name %>
        <% end %>
      </td>
      <td class="center"><%= quantity %></td>
      <td class="center"><%= number_to_currency product.price, 
        precision: Settings.product.precision %></td>
      <td class="center">
        <%= number_to_currency Accounting.item_total_cost(product.price,
          quantity), precision: Settings.product.precision %></td>
      <td class="center">
        <%= link_to t(".delete"), cart_path(product.id), method: :delete, 
          data: {confirm: t("carts.confirm_delete", name: product.name)} %>
      </td>
    </tr>
  <% end %>
<% end %>

app/views/carts/index.html.erb
<% provide :title, t(".cart_title") %>

<div class="wrapper">
  <div class="col-md-8 list-cart">
    <table class="table table-hover" id="cart-table">
      <thead>
        <th class="center"><%= t ".lbl_product" %></th>
        <th class="center"><%= t ".lbl_quantity" %></th>
        <th class="center"><%= t ".lbl_price" %></th>
        <th class="center"><%= t ".lbl_total_price" %></th> 
        <th class="center"><%= t ".lbl_option" %></th>
      </thead>
      <tbody>
        <% if @products.any? %>
          <%= render "carts/item" %>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-4">
    <div class="row">
      <div class="col-md-5">
        <h3><%= t ".lbl_total" %></h3>
      </div>
      <div class="col-md-7">
        <h3 class="total-price">
          <%= number_to_currency Accounting.cart_total_cost(@products),
            precision: Settings.product.precision %>
        </h3>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6 center">
        <%= link_to t(".btn_order"), "#", class: "btn btn-success" %>
      </div>
      <div class="col-md-6 center">
        <%= link_to t(".btn_cancel"), new_cart_path, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>