config/routes.rb
Rails.application.routes.draw do
  root "home_pages#home"
  
  devise_for :users
  namespace :admin do
    resources :users, only: [:index, :destroy, :update]
    resources :categories
    resources :products, except: :show
    resources :suggestions, only: [:index, :update, :destroy]
  end
  resources :suggestions, except: [:edit, :update, :show]
  resources :products, only: [:index, :show]
  resources :carts, except: [:edit, :update, :show]
  resources :users, only: [:show]
end

app/models/category.rb
class Category < ApplicationRecord
  acts_as_paranoid
  has_many :products, dependent: :destroy
  has_many :suggestions, dependent: :destroy

  validates :name, presence: true, uniqueness: {case_sensitive: false},
    length: {maximum: Settings.category.name_max_length}
  
  scope :order_date_desc, ->{order created_at: :desc}
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  load_and_authorize_resource param_method: [:update, :destroy]
  def index
    @categories = Category.order_date_desc.paginate page: params[:page], 
      per_page: Settings.category.per_page
  end
  
  def edit
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.new category_params
    if @category.save
      flash[:success] = t ".created"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".create_error"
      render :new
    end
  end

  def update
    if @category.update_attributes category_params
      flash[:success] = t ".updated"
      redirect_to admin_categories_path
    else
      flash.now[:danger] = t ".update_error"
      render :edit
    end
  end

  def destroy
    if @category.destroy
      flash[:success] = t ".deleted"
    else
      flash[:danger] = t ".delete_error"
    end
    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit :name
  end
end

app/views/admin/categories/_category.html.erb
<tr class="category">
  <td class="index"><%= index_for category_counter, @categories.current_page,
    Settings.category.per_page %></td>
  <td class="name"><%= category.name %></td>
  <td class="total-product"><%= category.products.size %></td>
  <td class="total-suggestion"><%= category.suggestions.size %></td>
  <td class="action">
    <%= link_to t(".edit"), edit_admin_category_path(category.id),
      class: "btn btn-primary btn-action" %>
    <%= link_to t(".delete"), [:admin, category], method: :delete,
      data: {confirm: t(".confirm_delete", name: category.name, 
        product: category.products.size, suggestion: category.suggestions.size)},
      class: "btn btn-danger btn-action" %>
  </td>
</tr>

app/views/admin/categories/_form.html.erb
<%= form_for [:admin, @category], html: {class: "form-horizontal category-form",
  id: "category_form"} do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="control-group">
    <%= f.label :name, t(".name") %>
    <div class="controls">
      <%= f.text_field :name, class: "form-control", id: "name",
        placeholder: t(".name_holder") %>
    </div>
  </div>
  <div class="form-actions add-category">
    <%= f.submit yield(:button_text), class: "btn btn-primary" %>
    <%= link_to t(".cancel"), :back, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/categories/edit.html.erb
<% provide :title, t(".edit", name: @category.name) %>
<% provide :button_text, t(".save_changes") %>
<div class="col-md-6 col-md-offset-3">
  <h1><%= t(".edit", name: @category.name) %></h1>
  <%= render "form" %>
</div>

app/views/admin/categories/index.html.erb
<% provide :title, t(".all_categories") %>
<div class="col-md-8 col-md-offset-2">
  <h1><%= t ".all_categories" %></h1>
  <%= link_to t(".add_category"), new_admin_category_path,
    class: "btn btn-success" %>
  <table class="table table-striped table-hover">
    <thead>
      <tr class="display-category">
        <th class="index"><%= t ".index" %></th>
        <th class="name"><%= t ".name" %></th>
        <th class="total-product"><%= t ".product" %></th>
        <th class="total-suggestion"><%= t ".suggestion" %></th>
        <th class="action"><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @categories %>
    </tbody>
  </table>
</div>

<div class="paginate">
  <%= will_paginate @categories %>
</div>

app/views/admin/categories/new.html.erb
<% provide :title, t(".add_category") %>
<% provide :button_text, t(".add_category") %>
<div class="col-md-6 col-md-offset-3">
  <h1><%= t ".add_category" %></h1>
  <%= render "form" %>
</div>