config/routes.rb
Rails.application.routes.draw do
  root "home_pages#home"
  
  devise_for :users
  namespace :admin do
    resources :users, only: [:index, :destroy, :update]
    resources :categories
    resources :products, except: :show
    resources :suggestions, only: [:index, :update, :destroy]
  end
  resources :suggestions, except: [:edit, :update, :show]
  resources :products, only: [:index, :show]
  resources :carts, except: [:edit, :update, :show]
  resources :users, only: [:show]
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  belongs_to :category
  has_many :order_items, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, 
    length: {maximum: Settings.product.name_max_length}
  validates :description, presence: true,
    length: {maximum: Settings.product.description_max_length}
  validates :price, presence: true, numericality: {only_integer: true}
  validate :image_size

  mount_uploader :image, PictureUploader
  
  delegate :name, to: :category, prefix: true, allow_nil: true
 
  scope :order_date_desc, ->{order created_at: :desc}
  scope :filter_category, ->category_id do
    where category_id: category_id if category_id.present?
  end
  
  private
  def image_size
    if image.size > Settings.product.image_max_size
      errors.add :image, I18n.t("admin.products.max_size_error")
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  load_and_authorize_resource
  before_action :load_categories, except: :destroy
  
  def index
    @products = Product.order_date_desc.paginate page: params[:page],
      per_page: Settings.product.per_page
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "admin.products.create.created"
      redirect_to admin_products_path
    else
      flash.now[:danger] = t "admin.products.create.create_error"
      render :new
    end
  end
  
  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "admin.products.update.updated"
      redirect_to admin_products_path
    else
      flash.now[:danger] = t "admin.products.update.update_error"
      render :edit
    end
  end

  def destroy
   if @product.destroy
      flash[:success] = t "admin.products.destroy.deleted"
    else
      flash[:danger] = t "admin.products.destroy.delete_error"
    end
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit :name, :category_id, :description, :price,
      :image
  end
  
  def load_categories
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @products = Product.filter_category(params[:category_id]).order_date_desc
      .paginate page: params[:page], per_page: Settings.product.per_page
  end

  def show
  end
end

app/views/admin/products/_form.html.erb
<%= form_for [:admin, @product], html: {multipart: true, 
  class: "form-horizontal product-form", id: "product_form"} do |f| %>
  <%= render "shared/error_messages", object: @product %>
  <div class="control-group">
    <%= f.label :category %>
    <%= f.select :category_id, options_for_select(
      @categories.collect{|category| [category.name, category.id]},
      params[:category_id]), {}, {class: "form-control"} %>
  </div>
  <div class="control-group">
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :description %>
    <%= f.text_area :description, rows: Settings.product.area_rows, 
      class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :price %>
    <%= f.text_field :price, class: "form-control" %>
  </div>
  <div class="control-group">
    <%= f.label :image %>
    <%= f.file_field :image, accept: Settings.product.image_accept %>
  </div>
  <div class="form-actions">
    <%= f.submit yield(:button_text), class: "btn btn-primary",
      id: "btn_product" %>
    <%= link_to t(".cancel"), admin_products_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/admin/products/_product.html.erb
<tr class="product">
  <td class="index"><%= index_for product_counter, @products.current_page,
    Settings.product.per_page %></td>
  <td class="image"><%= image_tag product.image.url, size: Settings.product.size %></td>  
  <td class="name"><%= product.name %></td>
  <td class="category"><%= product.category.name %></td>
  <td class="description"><%= product.description %></td>
  <td class="price"><%= t("admin.products.price_format", 
     price: (number_to_currency product.price, precision: 0)) %></td>
  <td class="action">
   <%= link_to t("admin.products.product.edit"), edit_admin_product_path(product.id),
      class: "btn btn-primary btn-action" %>
    <%= link_to t("admin.products.product.delete"), [:admin, product], method: :delete,
      data: {confirm: t("admin.products.product.confirm_delete", name: product.name,
        comments: product.comments.size)}, class: "btn btn-danger btn-action" %>
  </td>
</tr>

app/views/admin/products/edit.html.erb
<% provide :title, t(".edit_product") %>
<% provide :button_text, t(".save_changes") %>
<h1 class="edit_product"><%= t ".edit_product" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/admin/products/index.html.erb
<% provide :title, t(".all_products") %>
<h1><%= t ".all_products" %></h1>
<div class="md-col-12 ">
  <%= link_to t(".add_product"), new_admin_product_path,
    class: "btn btn-success" %>
</div>
<table class="table table-striped table-hover">
  <thead>
    <tr class="display-product">
      <th class="index"><%= t ".index" %></th>
      <th class="image"><%= t ".image" %></th>
      <th class="name"><%= t ".name" %></th>
      <th class="category"><%= t ".category" %></th>
      <th class="description"><%= t ".description" %></th>
      <th class="price"><%= t ".price" %></th>
      <th class="action"><%= t ".action" %></th>
    </tr>
  </thead>
  <tbody>
    <%= render @products %>
  </tbody>
</table>

<div class="paginate">
  <%= will_paginate @products %>
</div>

app/views/admin/products/new.html.erb
<% provide :title, t("admin.products.new.add_product") %>
<% provide :button_text, t("admin.products.new.create_product") %>
<h1 class="add_product"><%= t ".add_product" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>