config/routes.rb
Rails.application.routes.draw do
  root "home_pages#home"
  
  devise_for :users
  namespace :admin do
    resources :users, only: [:index, :destroy, :update]
    resources :categories
    resources :products, except: :show
    resources :suggestions, only: [:index, :update, :destroy]
  end
  resources :suggestions, except: [:edit, :update, :show]
  resources :products, only: [:index, :show]
  resources :carts, except: [:edit, :update, :show]
  resources :users, only: [:show]
end

app/models/product.rb
class Product < ApplicationRecord
  acts_as_paranoid
  belongs_to :category
  has_many :order_items, dependent: :destroy
  has_many :ratings, dependent: :destroy
  has_many :comments, dependent: :destroy

  validates :name, presence: true, 
    length: {maximum: Settings.product.name_max_length}
  validates :description, presence: true,
    length: {maximum: Settings.product.description_max_length}
  validates :price, presence: true, numericality: {only_integer: true}
  validate :image_size

  mount_uploader :image, PictureUploader
  
  delegate :name, to: :category, prefix: true, allow_nil: true
 
  scope :order_date_desc, ->{order created_at: :desc}
  scope :filter_category, ->category_id do
    where category_id: category_id if category_id.present?
  end
  
  private
  def image_size
    if image.size > Settings.product.image_max_size
      errors.add :image, I18n.t("admin.products.max_size_error")
    end
  end
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < Admin::BaseController
  load_and_authorize_resource
  before_action :load_categories, except: :destroy
  
  def index
    @products = Product.order_date_desc.paginate page: params[:page],
      per_page: Settings.product.per_page
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:success] = t "admin.products.create.created"
      redirect_to admin_products_path
    else
      flash.now[:danger] = t "admin.products.create.create_error"
      render :new
    end
  end
  
  def edit
  end

  def update
    if @product.update_attributes product_params
      flash[:success] = t "admin.products.update.updated"
      redirect_to admin_products_path
    else
      flash.now[:danger] = t "admin.products.update.update_error"
      render :edit
    end
  end

  def destroy
   if @product.destroy
      flash[:success] = t "admin.products.destroy.deleted"
    else
      flash[:danger] = t "admin.products.destroy.delete_error"
    end
    redirect_to admin_products_path
  end

  private
  def product_params
    params.require(:product).permit :name, :category_id, :description, :price,
      :image
  end
  
  def load_categories
    @categories = Category.all
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  load_and_authorize_resource
  
  def index
    @products = Product.filter_category(params[:category_id]).order_date_desc
      .paginate page: params[:page], per_page: Settings.product.per_page
  end

  def show
  end
end

app/views/products/_product.html.erb
<div class="col-md-3">
  <div class="col-md-12 frame-product">
  <div class="image">
    <%= image_tag product.image.url, size: Settings.product.size_small %>
  </div>
  <div class="information">
    <h4><%= link_to product.name, product_path(product) %></h4>
    <h5><i><b><%= number_to_currency product.price,
      precision: Settings.product.precision %></b></i></h5>
    <%= form_tag carts_path do %>
      <%= hidden_field_tag :product_id, product.id %>
      <%= hidden_field_tag :quantity, Settings.cart.init_quantity %>
      <%= button_tag class: "btn btn-primary" do %>
        <i class="glyphicon glyphicon-shopping-cart"></i>
        <%= t "products.add_to_cart" %>
      <% end %>
    <% end %>
  </div>
  </div>
</div>

app/views/products/index.html.erb
<% provide :title, t("products.title") %>
<h1><%= t "products.list" %></h1>

<div class="row products-page">
  <div class="section">
    <%= render @products %>
  </div>
</div>

<div class="row paginate">
  <%= will_paginate @products %>
</div>

app/views/products/show.html.erb
<% provide :title, t("products.header", name: @product.name) %>

<div class="container-fluid product-detail">
  <div class="row">
    <div class="col-md-offset-1 col-md-3">
      <div class="product_image">
        <%= image_tag @product.image.url, size: Settings.product.size_big  %>
      </div>
    </div>
    <div class="col-md-7">
      <table class="table ">
        <theader>
          <tr>
            <th><%= t "products.name" %></th>
            <td><%= @product.name %></td>
          </tr>
        </theader>
        <tbody>
          <tr>
            <th><%= t "products.category" %></th>
            <td><%= @product.category_name %></td>
          </tr>
          <tr>
            <th><%= t "products.description" %></th>
            <td><%= @product.description %></td>
          </tr>
          <tr>
            <th><%= t "products.lbl_price" %></th>
            <td><%= number_to_currency @product.price,
              precision: Settings.product.precision %></td>
          </tr>
          <tr>
            <th><%= t "products.rating" %></th>
            <td><%= @product.avg_rating %></td>
          </tr>
          <tr>
            <th><%= t "products.quantity" %></th>
            <td>
              <%= form_tag carts_path do %>
                <%= hidden_field_tag :product_id, @product.id %>
                <%= number_field_tag :quantity, Settings.cart.init_quantity,
                  min: Settings.cart.minimum_quantity, class: "quantity" %>
                <%= button_tag class: "btn btn-primary" do %>
                  <i class="glyphicon glyphicon-shopping-cart"></i>
                  <%= t "products.add_to_cart" %>
                <% end %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>